apiVersion: apps/v1
kind: Deployment
  labels:
    app: leader-elector
  name: leaderelection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderelection
  template:
    metadata:
      labels:
        app: leaderelection
    spec:
      containers:
        - name: leader-elector
        - image:
          env:
            - name: NAME
              value: .Values.name
            - name: GIST_ID
              value: .Values.gist
            - name: GITHUB_API_TOKEN
              value: .Values.token
